---
title: "Graphics with ggplot2"
author: "Dave"
date: "October 22, 2018"
output: html_document
---
## Load Package
```{r packages}
# install and load tidyverse
##install.packages("tidyverse") # note on Windows use double quotes
library(tidyverse)
```

## Load NP Data
```{r load_data}
#National Parks in California
ca <-read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with California ("ca")dataset
```{r}
head(ca)
View(ca)
```

Plot visitation to all CA NAtional Parks over time
```{r}
ggplot(data = ca) + 
  geom_point(aes(x= year, y= visitors))
```

```{r}
ggplot(data = ca) + 
  geom_point(aes(x= year, y= visitors, color = park_name)) +
  labs(x ="Year", y ="Vistors", title = "Southeast National Park Vistitors")
```

```{r}
head(se)
View(se)
```

```{r}
ggplot(data = se) + 
  geom_point(aes(x= year, y= visitors, color = state)) +
  labs(x ="Year", y ="Vistors", title = "Southeast National Park Vistors", angle = 45)+
  theme_minimal()
```

```{r}
ggplot(data = se) + 
  geom_point(aes(x= year, y= visitors, color = state)) +
  xlab("Years") +
  ylab("Visitors") +
  ggtitle("Visitors by State")+
  theme(legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, size = 12))
      
```

```{r}
ggplot(data=se)+
  geom_point(aes(x = year, y = visitors, color = park_name))+
  facet_wrap(~ state, scales = "free")
```
#geoms
```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors, color = park_name), alpha = 0.4, width = 0.1)
```

```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()
```
## Multiple geoms on one plot
```{r}
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() + 
  geom_line() + 
  geom_smooth()
  

```

```{r}
#install.packages("ggthemes")
library(ggthemes)
```
#Bar Charts
```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  theme_minimal()

```
#Save ggplot 
```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) + 
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.jpg", myplot)
```

# plotly
```{r}
#install.packages("plotly")
library(plotly)

```

```{r}
acad_vis <- ggplot(data = acadia, aes(x = year, y = visitors)) + 
  geom_point() +
  geom_line() +
  geom_smooth(color = "red") +
  labs(title = "Acadia National Park Visitation",
       y = "Visitation",
       x = "Year") +
  theme_bw()
ggplotly(acad_vis)

```

