---
title: "Wrangling"
author: "Dave"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse) #install.packages("tidyverse")
```

## Read Data
This is gapminder dataset
```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

#inspect the data
gapminder #looks at all the data
head(gapminder)
tail(gapminder, 2) #looks at the last 2 columns 

# summary stats
str(gapminder)
summary(gapminder)

#install.packages("skimr")
skimr::skim(gapminder)

names(gapminder)
dim(gapminder)
ncol(gapminder)
nrow(gapminder)

# reverse-engineer dim
c(nrow(gapminder), ncol(gapminder))

```

## Dplyer
```{r}
#filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru", "Italy"))
filter(gapminder, country == "Mexico", year == 2002)
```

## Finding the mean of a column 
```{r}
sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp) # $ lets you look at just one column 

```

## Select by columns
```{r}
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp)

#select and filter
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

```
## The pipe operator 
```{r}
gapminder %>% head(3)
# is equivalent to:
head(gapminder, 3)
# improve with pipe
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)

```

```{r}
# mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

## Challenge: find max gpd per cap of Egypt and Vietnam. Create a new column
gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  mutate(maxgdp = max(gdp))

#same as above but did not need to repeat the mutate 
gapminder %>% 
  filter(country %in% c("Egypt","Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap, maxgdp = max(gdp))
```

## Group by 
```{r}
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()
```

```{r}
gap_grouped <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap,
         min_gdp = min(gdp)) %>% 
  ungroup()
```

```{r}
#with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarise(max_gdp = max(gdp)) %>% 
  ungroup()
```


##arragnes columns
```{r}
#with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarise(max_gdp = max(gdp)) %>% 
  ungroup() %>%
  arrange(-max_gdp) #another way to arrange is decending order
  #arrange(desc(max_gdp))
```

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() #12 observations

## create a new gapminder variable with only 2007 data
gap2007 <- gapminder %>% 
  filter(year == 2007)

gap2007 %>% dim()

# left_join gap2007 to co2, left joins are easier to add into a chain or code, may need to use code that operates on the column position 
lj <- left_join(gap2007, co2, by = "country")
#another way to write
lj <- gap2007 %>% 
  left_join(co2, by = "country")

##right_join
rj <- right_join(gap2007,co2, by = "country")
#same as
lj2 <- left_join(co2, gap2007, by = "country")
```


